workflows:
  ios-preview:
    name: AgentDashboard - iOS Simulator Preview
    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
        DERIVED_DATA: "$CM_BUILD_DIR/DerivedData"

    scripts:
      - name: Clean DerivedData (hygiene)
        script: |
          rm -rf "$DERIVED_DATA" || true
          rm -rf "$HOME/Library/Developer/Xcode/DerivedData" || true

      - name: Resolve Swift Package Dependencies (allow macros/plugins)
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -skipMacroValidation

      - name: Build .app for the iOS Simulator (no code signing)
        script: |
          set -x
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

      - name: Sanity check - did the .app appear?
        script: |
          APP_PATH="$(/usr/bin/find "$DERIVED_DATA/Build/Products/Debug-iphonesimulator" -maxdepth 1 -name '*.app' -print -quit)"
          if [[ -z "${APP_PATH:-}" ]]; then
            echo "❌ Build succeeded but no .app found in Debug-iphonesimulator"
            exit 1
          fi
          echo "✅ Found simulator app: $APP_PATH"

    artifacts:
      - $CM_BUILD_DIR/DerivedData/Build/Products/Debug-iphonesimulator/*.app