workflows:
  ios-app-workflow:
    name: iOS AgentDashboard Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
      xcode: 16.0
    scripts:
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          cd iOS-App/AgentDashboard
          xcodebuild -project AgentDashboard.xcodeproj \
                     -scheme AgentDashboard \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                     -configuration Debug \
                     build
      - name: Archive Build Output
        script: |
          cd iOS-App/AgentDashboard
          echo "Searching for build outputs..."
          find . -name "*.app" -type d | head -10
          find . -name "AgentDashboard.app" -type d | head -5
          
          # Check common build locations
          ls -la build/ 2>/dev/null || echo "No build/ directory"
          ls -la DerivedData/ 2>/dev/null || echo "No DerivedData/ directory"  
          ls -la ~/Library/Developer/Xcode/DerivedData/ 2>/dev/null || echo "No user DerivedData"
          
          # Create artifacts directory
          mkdir -p artifacts
          
          # Find and copy app bundle
          APP_PATH=$(find . -name "AgentDashboard.app" -type d | head -1)
          if [ ! -z "$APP_PATH" ]; then
            echo "Found app at: $APP_PATH"
            cp -r "$APP_PATH" artifacts/
            ls -la artifacts/
          else
            echo "No app bundle found - listing build contents:"
            find . -type d -name "*build*" -exec ls -la {} \; 2>/dev/null
          fi
    artifacts:
      - artifacts/**/AgentDashboard.app
      - artifacts/**/*.ipa
    publishing:
      email:
        recipients:
          - georgest32@example.com
        notify:
          success: true
          failure: true