workflows:
  ios-tca-dashboard:
    name: iOS TCA Dashboard Build  
    max_build_duration: 120
    instance_type: mac_mini_m2  # Required for Xcode 16.x
    
    environment:
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
        BUNDLE_ID: "com.unity.claude.automation.dashboard"
      # CRITICAL FIX: Upgrade from 16.0 to 16.2 to resolve TCA XCSwiftPackageProductDependency errors
      xcode: 16.2  
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
          
    scripts:
      - name: Skip Xcode Macro Fingerprint Validation
        script: |
          # Required for TCA macros to work in CI/CD environment 
          # Research confirmed this resolves "CasePathsMacros must be enabled" errors
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
          
      - name: Force Complete Cache Reset
        script: |
          # Comprehensive cache clearing to force fresh build with latest git changes
          rm -rf ~/Library/Caches/org.swift.swiftpm
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/org.swift.swiftpm  
          rm -rf ~/.swiftpm/xcode/
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          # Verify git changes are present
          cd iOS-App/AgentDashboard
          echo "=== Current Git Status ==="
          git log --oneline -3
          echo "=== Verifying SystemStatus removal ==="
          grep -n "struct SystemStatus" AgentDashboard/Models/Models.swift || echo "SystemStatus successfully removed from Models.swift"
          echo "=== Force fresh checkout ==="  
          git checkout HEAD -- AgentDashboard/Models/Models.swift
          
      - name: Resolve Swift Package Dependencies
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard  
          pwd
          ls -la AgentDashboard.xcodeproj
          xcodebuild -skipMacroValidation \
            -resolvePackageDependencies \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard
            
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          pwd
          xcodebuild -skipMacroValidation \
            build \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: Archive Build Artifacts
        script: |
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          mkdir -p build/artifacts
          
          # Find and copy the built app
          DERIVED_DATA=$(find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard-*" -type d | head -1)
          if [ ! -z "$DERIVED_DATA" ]; then
            find "$DERIVED_DATA" -name "AgentDashboard.app" -type d | head -1 | xargs -I {} cp -r {} build/artifacts/
            echo "TCA iOS app successfully built and archived!"
          else
            echo "Build completed but no app bundle found"
          fi
          
    artifacts:
      - iOS-App/AgentDashboard/build/artifacts/**/*
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - developer@unity-claude-automation.com
        notify:
          success: true
          failure: true