workflows:
  ios-tca-dashboard:
    name: iOS TCA Dashboard
    environment:
      xcode: 16.4
      vars:
        APP_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        APP_SCHEME: "AgentDashboard"

    scripts:
      - name: Prepare build machine
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "Xcode: $(xcodebuild -version)"
          swift --version

      - name: Resolve Swift Package Dependencies (allow macros/plugins)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          cd "$CM_BUILD_DIR/iOS-App/AgentDashboard"
          xcodebuild -resolvePackageDependencies \
            -project AgentDashboard.xcodeproj \
            -skipMacroValidation \
            -skipPackagePluginValidation

      - name: Clean DerivedData (fresh build)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          rm -rf "$CM_BUILD_DIR/DerivedData"

      - name: Build for iOS Simulator (arm64, no global ARCH overrides)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          export MACOSX_DEPLOYMENT_TARGET=13.0

          DERIVED="$CM_BUILD_DIR/DerivedData"
          BUNDLE="$CM_BUILD_DIR/build.xcresult"
          LOG="$CM_BUILD_DIR/xcodebuild.log"

          xcodebuild \
            -project "$APP_PROJECT" \
            -scheme "$APP_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath "$DERIVED" \
            -resultBundlePath "$BUNDLE" \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            ONLY_ACTIVE_ARCH=YES \
            ENABLE_USER_SCRIPT_SANDBOXING=NO \
            build | tee "$LOG"

      - name: Extract compiler errors (if any)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          if [[ -f "$CM_BUILD_DIR/xcodebuild.log" ]]; then
            echo "=== Errors from xcodebuild.log ==="
            grep -nE " error: |could not be found for macro|malformed response" "$CM_BUILD_DIR/xcodebuild.log" || true
          else
            echo "No xcodebuild.log found"
          fi

      - name: Create preview artifacts (validate app)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          DERIVED="$CM_BUILD_DIR/DerivedData/Build/Products/Debug-iphonesimulator"
          APP_DIR="$(find "$DERIVED" -maxdepth 1 -type d -name '*.app' -print -quit || true)"

          [[ -n "${APP_DIR:-}" ]] || { echo "❌ No .app produced (build failed)."; exit 1; }

          PLIST="$APP_DIR/Info.plist"
          [[ -f "$PLIST" ]] || { echo "❌ $APP_DIR has no Info.plist — invalid app."; exit 1; }

          EXEC=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$PLIST" 2>/dev/null || true)
          [[ -n "${EXEC:-}" && -f "$APP_DIR/$EXEC" ]] || { echo "❌ Missing main executable — app wasn’t linked."; exit 1; }

          mkdir -p "$CM_ARTIFACTS"

          (cd "$(dirname "$APP_DIR")" && /usr/bin/zip -qry "$CM_ARTIFACTS/app-preview.zip" "$(basename "$APP_DIR")")
          cp -R "$APP_DIR" "$CM_ARTIFACTS/AgentDashboard.app"

          echo "✅ Preview artifact: $CM_ARTIFACTS/app-preview.zip"
          ls -lah "$CM_ARTIFACTS"

    artifacts:
      - $CM_ARTIFACTS/app-preview.zip
      - $CM_ARTIFACTS/AgentDashboard.app

    publishing:
      publish:
        app_preview: true
