workflows:
  ios-app-workflow:
    name: iOS AgentDashboard Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Automatic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.unity-claude.AgentDashboard
      vars:
        XCODE_WORKSPACE: "iOS-App/AgentDashboard/AgentDashboard.xcworkspace"
        XCODE_SCHEME: "AgentDashboard"
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain'
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # For now, skip code signing for demo build
          echo "Skipping code signing for demo build"
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd iOS-App/AgentDashboard
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/**/AgentDashboard.ipa
    publishing:
      email:
        recipients:
          - georgest32@example.com
        notify:
          success: true
          failure: true