workflows:
  ios-app-workflow:
    name: iOS AgentDashboard Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Automatic
    environment:
      vars:
        XCODE_WORKSPACE: "iOS-App/AgentDashboard/AgentDashboard.xcworkspace"
        XCODE_SCHEME: "AgentDashboard"
      xcode: 16.0
    scripts:
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          cd iOS-App/AgentDashboard
          xcodebuild -workspace AgentDashboard.xcworkspace \
                     -scheme AgentDashboard \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                     -configuration Debug \
                     build
      - name: Archive Build Output
        script: |
          cd iOS-App/AgentDashboard
          mkdir -p build
          cp -r build/Debug-iphonesimulator/AgentDashboard.app build/ || echo "App bundle not found - build may have failed"
    artifacts:
      - build/**/AgentDashboard.ipa
    publishing:
      email:
        recipients:
          - georgest32@example.com
        notify:
          success: true
          failure: true