workflows:
  ios-tca-dashboard:
    name: iOS TCA Dashboard Build  
    max_build_duration: 120
    instance_type: mac_mini_m2  # Required for Xcode 16.x
    
    environment:
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
        BUNDLE_ID: "com.unity.claude.automation.dashboard"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
      # CRITICAL FIX: Upgrade to 16.4+ to support -enablePackageFeature for TCA macros
      xcode: latest  
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
          
    scripts:
      - name: Set environment for simulator builds
        script: |
          export DEVELOPER_DIR=/Applications/Xcode.app
          export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
          export DYLD_ROOT_PATH="$SDKROOT"
          echo "DEVELOPER_DIR=$DEVELOPER_DIR" >> $CM_ENV
          echo "SDKROOT=$SDKROOT" >> $CM_ENV
          echo "DYLD_ROOT_PATH=$DYLD_ROOT_PATH" >> $CM_ENV
          
      - name: Select iOS 18.5 simulator matching SDK
        script: |
          set -e
          echo "=== Available iOS 18.5 simulators ==="
          xcrun simctl list devices | grep "iOS 18" || true
          
          # Try to find iOS 18.5 simulator first, fall back to any iOS 18.x
          DEVICE_NAME="iPhone 16 Pro"
          OS_VERSION="18.5"
          
          # Check if specific version exists
          if xcrun simctl list devices | grep -q "$DEVICE_NAME.*$OS_VERSION"; then
            echo "Using $DEVICE_NAME with iOS $OS_VERSION"
          else
            # Fall back to latest iOS 18.x
            OS_VERSION="18"
            echo "iOS 18.5 not found, using latest iOS 18.x"
          fi
          
          # Boot the simulator
          xcrun simctl boot "$DEVICE_NAME" || true
          echo "SIMULATOR_NAME=$DEVICE_NAME" >> $CM_ENV
          echo "SIMULATOR_OS=$OS_VERSION" >> $CM_ENV

      - name: Build with full diagnostics
        script: |
          set -o pipefail
          source $CM_ENV
          # Build with iOS 18.5 simulator matching SDK
          xcodebuild \
            -project iOS-App/AgentDashboard/AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME,OS=$SIMULATOR_OS" \
            -configuration Debug \
            -resolvePackageDependencies \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -resultBundlePath "$CM_BUILD_DIR/build.xcresult" \
            clean build \
            | tee $CM_BUILD_DIR/xcodebuild.log || true

      - name: Extract compiler errors from result bundle
        script: |
          RESULT="${CM_BUILD_DIR:-$PWD}/build.xcresult"
          
          if [ -d "$RESULT" ] || [ -f "$RESULT" ]; then
            echo "=== Human-readable compiler errors ==="
            xcrun xcresulttool get --format humanReadable --path "$RESULT" | awk '/[Ee]rror:|[Ee]rrors:/, /^$/' || true
          
            echo "=== Detailed JSON error extraction ==="
            xcrun xcresulttool get --path "$RESULT" --format json | python3 -c "
          import json, sys, urllib.parse
          j = json.load(sys.stdin)
          
          errors = []
          def walk(x):
              if isinstance(x, dict):
                  if x.get('issueType') == 'error':
                      msg = x.get('message', {}).get('text', '')
                      loc = x.get('documentLocationInCreatingWorkspace', {}) or {}
                      url = loc.get('url') or x.get('documentURL', '')
                      if url.startswith('file://'):
                          url = urllib.parse.unquote(url.replace('file://', ''))
                      line = loc.get('line') or loc.get('startingLineNumber') or ''
                      errors.append((msg, url, line))
                  for v in x.values():
                      walk(v)
              elif isinstance(x, list):
                  for v in x:
                      walk(v)
          
          walk(j)
          if not errors:
              print('No compilation errors found in result bundle')
          else:
              for msg, url, line in errors:
                  print('ERROR:', msg)
                  if url:  print('  File:', url)
                  if line: print('  Line:', line)
                  print()
          "
          else
            echo "No result bundle found at $RESULT"
          fi

      - name: Dump Swift diagnostics
        script: |
          find ~/Library/Developer/Xcode/DerivedData -name "*.dia" -exec strings {} \; | tee $CM_BUILD_DIR/diagnostics.txt || true

      - name: Grep APIClient errors from log
        script: |
          echo "=== APIClient.swift compilation context ==="
          grep -n "APIClient.swift" $CM_BUILD_DIR/xcodebuild.log -C10 || true

      - name: Skip Xcode Macro Fingerprint Validation
        script: |
          # Required for TCA macros to work in CI/CD environment 
          # Research confirmed this resolves "CasePathsMacros must be enabled" errors
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
          
      - name: Force Complete Cache Reset
        script: |
          # Comprehensive cache clearing to force fresh build with latest git changes
          rm -rf ~/Library/Caches/org.swift.swiftpm
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/org.swift.swiftpm  
          rm -rf ~/.swiftpm/xcode/
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          # Verify git changes are present
          cd iOS-App/AgentDashboard
          echo "=== Current Git Status ==="
          git log --oneline -3
          echo "=== Verifying SystemStatus removal ==="
          grep -n "struct SystemStatus" AgentDashboard/Models/Models.swift || echo "SystemStatus successfully removed from Models.swift"
          echo "=== Force fresh checkout ==="  
          git checkout HEAD -- AgentDashboard/Models/Models.swift
          
      - name: Resolve Swift Package Dependencies (allow macros/plugins)
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard  
          pwd
          ls -la AgentDashboard.xcodeproj
          # Resolve packages with macro/plugin validation skipped for CI
          xcodebuild -resolvePackageDependencies \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -skipMacroValidation \
            -skipPackagePluginValidation
            
      - name: Clean DerivedData to avoid stale state
        script: |
          echo "Cleaning DerivedData to ensure fresh build..."
          rm -rf ~/Library/Developer/Xcode/DerivedData
            
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          # Load environment variables
          source $CM_ENV
          # CRITICAL: Set macOS 13.0 target for TCA macro host compilation
          export MACOSX_DEPLOYMENT_TARGET=13.0
          echo "Building with $SIMULATOR_NAME on iOS $SIMULATOR_OS"
          pwd
          # Build with iOS 18.5 simulator matching SDK
          xcodebuild build \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME,OS=$SIMULATOR_OS" \
            -configuration Debug \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -derivedDataPath "$CM_BUILD_DIR/DerivedData" \
            -resultBundlePath "$CM_BUILD_DIR/main-build.xcresult" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO || true
            
      - name: Extract main build errors
        script: |
          RESULT="${CM_BUILD_DIR:-$PWD}/main-build.xcresult"
          
          if [ -d "$RESULT" ] || [ -f "$RESULT" ]; then
            echo "=== Main build human-readable errors ==="
            xcrun xcresulttool get --format humanReadable --path "$RESULT" | awk '/[Ee]rror:|[Ee]rrors:/, /^$/' || true
            
            echo "=== Main build detailed errors ==="
            xcrun xcresulttool get --path "$RESULT" --format json | python3 -c "
          import json, sys, urllib.parse
          j = json.load(sys.stdin)
          
          errors = []
          def walk(x):
              if isinstance(x, dict):
                  if x.get('issueType') == 'error':
                      msg = x.get('message', {}).get('text', '')
                      loc = x.get('documentLocationInCreatingWorkspace', {}) or {}
                      url = loc.get('url') or x.get('documentURL', '')
                      if url.startswith('file://'):
                          url = urllib.parse.unquote(url.replace('file://', ''))
                      line = loc.get('line') or loc.get('startingLineNumber') or ''
                      errors.append((msg, url, line))
                  for v in x.values():
                      walk(v)
              elif isinstance(x, list):
                  for v in x:
                      walk(v)
          
          walk(j)
          if not errors:
              print('No compilation errors found in main build')
          else:
              for msg, url, line in errors:
                  print('ERROR:', msg)
                  if url:  print('  File:', url)
                  if line: print('  Line:', line)
                  print()
          "
          else
            echo "No result bundle found at $RESULT"
          fi
            
      - name: Archive Build Artifacts
        script: |
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          mkdir -p build/artifacts
          
          # Find and copy the built app
          DERIVED_DATA=$(find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard-*" -type d | head -1)
          if [ ! -z "$DERIVED_DATA" ]; then
            find "$DERIVED_DATA" -name "AgentDashboard.app" -type d | head -1 | xargs -I {} cp -r {} build/artifacts/
            echo "TCA iOS app successfully built and archived!"
          else
            echo "Build completed but no app bundle found"
          fi
          
    artifacts:
      - iOS-App/AgentDashboard/build/artifacts/**/*
      - $CM_BUILD_DIR/xcodebuild.log
      - $CM_BUILD_DIR/diagnostics.txt
      - $CM_BUILD_DIR/build.xcresult
      - $CM_BUILD_DIR/main-build.xcresult
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - developer@unity-claude-automation.com
        notify:
          success: true
          failure: true