workflows:
  ios-app-workflow:
    name: iOS AgentDashboard Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
      xcode: 16.0
    scripts:
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          cd iOS-App/AgentDashboard
          xcodebuild -project AgentDashboard.xcodeproj \
                     -scheme AgentDashboard \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                     -configuration Debug \
                     build
      - name: Archive Build Output
        script: |
          cd iOS-App/AgentDashboard
          echo "Searching for build outputs in derived data..."
          
          # Look in derived data folder
          DERIVED_DATA=$(find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard-*" -type d | head -1)
          echo "Derived data path: $DERIVED_DATA"
          
          if [ ! -z "$DERIVED_DATA" ]; then
            echo "Contents of derived data:"
            ls -la "$DERIVED_DATA/Build/Products/" 2>/dev/null || echo "No Build/Products in derived data"
            
            # Look for the app in derived data
            find "$DERIVED_DATA" -name "*.app" -type d | head -5
          fi
          
          # Also search globally for any .app files
          echo "Searching globally for app bundles..."
          find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard.app" -type d 2>/dev/null | head -5
          
          # Create artifacts directory
          mkdir -p artifacts
          
          # Find and copy app bundle from derived data
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard.app" -type d | head -1)
          if [ ! -z "$APP_PATH" ]; then
            echo "Found app at: $APP_PATH"
            cp -r "$APP_PATH" artifacts/
            echo "Copied app to artifacts:"
            ls -la artifacts/
          else
            echo "No app bundle found. Checking all derived data build products:"
            find ~/Library/Developer/Xcode/DerivedData -path "*/Build/Products/*" -name "*.app" -type d | head -10
          fi
    artifacts:
      - artifacts/**/AgentDashboard.app
      - artifacts/**/*.ipa
    publishing:
      email:
        recipients:
          - georgest32@example.com
        notify:
          success: true
          failure: true