workflows:
  ios-tca-dashboard:
    name: iOS TCA Dashboard Build  
    max_build_duration: 120
    instance_type: mac_mini_m2  # Required for Xcode 16.x
    
    environment:
      vars:
        XCODE_PROJECT: "iOS-App/AgentDashboard/AgentDashboard.xcodeproj"
        XCODE_SCHEME: "AgentDashboard"
        BUNDLE_ID: "com.unity.claude.automation.dashboard"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
      # CRITICAL FIX: Upgrade from 16.0 to 16.2 to resolve TCA XCSwiftPackageProductDependency errors
      xcode: 16.2  
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
          
    scripts:
      - name: Select an available iPhone simulator
        script: |
          set -e
          DEVICE_ID=$(xcrun simctl list devices available | \
            awk -F '[()]' '/iPhone 1[4-9]|iPhone SE \(3rd generation\)/ {print $2; exit}')
          if [ -z "$DEVICE_ID" ]; then
            echo "No suitable iPhone simulator found"
            exit 70
          fi
          echo "Using simulator id: $DEVICE_ID"
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "$DEVICE_ID" > $CM_BUILD_DIR/sim_id.txt

      - name: Build with full diagnostics
        script: |
          set -o pipefail
          DEVICE_ID=$(cat $CM_BUILD_DIR/sim_id.txt)
          xcodebuild \
            -project iOS-App/AgentDashboard/AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -sdk iphonesimulator \
            -destination "id=$DEVICE_ID" \
            -configuration Debug \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -skipPackageSignatureValidation \
            | tee $CM_BUILD_DIR/xcodebuild.log

      - name: Dump Swift diagnostics
        script: |
          find ~/Library/Developer/Xcode/DerivedData -name "*.dia" -exec strings {} \; | tee $CM_BUILD_DIR/diagnostics.txt || true

      - name: Grep APIClient errors
        script: |
          grep -n "APIClient.swift" $CM_BUILD_DIR/xcodebuild.log -C5 || true

      - name: Skip Xcode Macro Fingerprint Validation
        script: |
          # Required for TCA macros to work in CI/CD environment 
          # Research confirmed this resolves "CasePathsMacros must be enabled" errors
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
          
      - name: Force Complete Cache Reset
        script: |
          # Comprehensive cache clearing to force fresh build with latest git changes
          rm -rf ~/Library/Caches/org.swift.swiftpm
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/org.swift.swiftpm  
          rm -rf ~/.swiftpm/xcode/
          rm -rf ~/Library/Caches/com.apple.dt.Xcode
          # Verify git changes are present
          cd iOS-App/AgentDashboard
          echo "=== Current Git Status ==="
          git log --oneline -3
          echo "=== Verifying SystemStatus removal ==="
          grep -n "struct SystemStatus" AgentDashboard/Models/Models.swift || echo "SystemStatus successfully removed from Models.swift"
          echo "=== Force fresh checkout ==="  
          git checkout HEAD -- AgentDashboard/Models/Models.swift
          
      - name: Resolve Swift Package Dependencies
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard  
          pwd
          ls -la AgentDashboard.xcodeproj
          xcodebuild \
            -resolvePackageDependencies \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -skipPackageSignatureValidation
            
      - name: Build for iOS Simulator (No Code Signing)
        script: |
          # Fix working directory issue - use absolute paths
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          # CRITICAL: Set macOS 13.0 target for TCA macro host compilation
          export MACOSX_DEPLOYMENT_TARGET=13.0
          # Use the previously selected simulator
          DEVICE_ID=$(cat $CM_BUILD_DIR/sim_id.txt)
          echo "Building with simulator ID: $DEVICE_ID"
          pwd
          xcodebuild \
            build \
            -project AgentDashboard.xcodeproj \
            -scheme AgentDashboard \
            -destination "id=$DEVICE_ID" \
            -configuration Debug \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -skipPackageSignatureValidation \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: Archive Build Artifacts
        script: |
          cd $CM_BUILD_DIR/iOS-App/AgentDashboard
          mkdir -p build/artifacts
          
          # Find and copy the built app
          DERIVED_DATA=$(find ~/Library/Developer/Xcode/DerivedData -name "AgentDashboard-*" -type d | head -1)
          if [ ! -z "$DERIVED_DATA" ]; then
            find "$DERIVED_DATA" -name "AgentDashboard.app" -type d | head -1 | xargs -I {} cp -r {} build/artifacts/
            echo "TCA iOS app successfully built and archived!"
          else
            echo "Build completed but no app bundle found"
          fi
          
    artifacts:
      - iOS-App/AgentDashboard/build/artifacts/**/*
      - $CM_BUILD_DIR/xcodebuild.log
      - $CM_BUILD_DIR/diagnostics.txt
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - developer@unity-claude-automation.com
        notify:
          success: true
          failure: true