# Generate-Ollama-Enhanced-Documentation.ps1
# AI-powered documentation generation using Ollama Code Llama 13B
# Enhanced Documentation System v2.0.0 - Intelligent Documentation
# Date: 2025-08-29

param(
    [string]$ModulePath = ".\Modules\Unity-Claude-CPG\Core\Predictive-Evolution.psm1",
    [string]$OutputPath = ".\docs\ollama-enhanced",
    [switch]$AnalyzeAll,
    [string]$Model = "codellama:13b"
)

function Write-OllamaLog {
    param([string]$Message, [string]$Level = "Info")
    $color = @{ "Info" = "White"; "Success" = "Green"; "Warning" = "Yellow"; "Error" = "Red"; "AI" = "Magenta" }[$Level]
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] [$Level] $Message" -ForegroundColor $color
}

Write-Host "=== Ollama-Enhanced Documentation Generation ===" -ForegroundColor Cyan
Write-Host "Using Code Llama 13B for intelligent code analysis and documentation" -ForegroundColor Magenta

try {
    # Step 1: Verify Ollama is operational
    Write-OllamaLog "Testing Ollama connection..." -Level "Info"
    
    $ollamaStatus = Test-OllamaConnection
    
    if ($ollamaStatus.Available) {
        Write-OllamaLog "Ollama OPERATIONAL: $($ollamaStatus.Message)" -Level "Success"
        Write-OllamaLog "Available models: $($ollamaStatus.Models.Count)" -Level "Info"
        
        # Show available models
        foreach ($modelInfo in $ollamaStatus.Models) {
            $sizeGB = [math]::Round($modelInfo.size / 1GB, 1)
            Write-OllamaLog "  Model: $($modelInfo.name) (${sizeGB}GB)" -Level "AI"
        }
        
    } else {
        Write-OllamaLog "Ollama NOT AVAILABLE: $($ollamaStatus.Message)" -Level "Error"
        Write-OllamaLog "Start Ollama with: ollama serve" -Level "Info"
        return
    }
    
    # Create output directory
    if (-not (Test-Path $OutputPath)) {
        New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    }
    
    # Step 2: Generate AI-enhanced documentation for specific module
    if (-not $AnalyzeAll -and (Test-Path $ModulePath)) {
        Write-OllamaLog "Analyzing module with AI: $ModulePath" -Level "AI"
        
        $moduleName = [System.IO.Path]::GetFileNameWithoutExtension($ModulePath)
        $content = Get-Content $ModulePath -Raw
        
        # Create AI prompt for code analysis
        $analysisPrompt = @"
Analyze this PowerShell module and provide comprehensive documentation:

Module: $moduleName
Code:
$content

Please provide:
1. Module purpose and overview
2. Key functions and their purposes  
3. Design patterns used
4. Integration points with other modules
5. Usage examples
6. Best practices and recommendations

Format as markdown with clear sections.
"@
        
        Write-OllamaLog "Sending code to AI for analysis (this may take 60-120 seconds)..." -Level "AI"
        
        try {
            # Use Ollama to analyze the code
            $aiAnalysis = Invoke-OllamaGenerate -Prompt $analysisPrompt -Model $Model -MaxTokens 4096
            
            if ($aiAnalysis) {
                # Create enhanced documentation
                $enhancedDoc = @"
# $moduleName - AI-Enhanced Documentation
**Generated by**: Ollama Code Llama 13B
**Timestamp**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
**Module Path**: $ModulePath

## AI Analysis

$aiAnalysis

## Module Integration
This module is part of the Enhanced Documentation System v2.0.0 and integrates with:
- 🤖 **LangGraph AI**: http://localhost:8000 (Multi-agent workflows)
- 👥 **AutoGen GroupChat**: http://localhost:8001 (Multi-agent collaboration)
- 📊 **Week 4 Features**: Predictive analysis and maintenance forecasting

## System Context
Generated as part of the Enhanced Documentation System v2.0.0 deployment with:
- Complete AI integration (LangGraph + AutoGen + Ollama)
- Week 4 predictive analysis capabilities
- Production-ready Docker containerization

---
*Enhanced by Ollama Code Llama 13B - AI-Powered Documentation*
"@
                
                $docPath = "$OutputPath\$moduleName-ai-enhanced.md"
                $enhancedDoc | Out-File -FilePath $docPath -Encoding UTF8
                
                Write-OllamaLog "AI-enhanced documentation generated: $moduleName-ai-enhanced.md" -Level "Success"
                Write-OllamaLog "AI analysis length: $($aiAnalysis.Length) characters" -Level "AI"
                
            } else {
                Write-OllamaLog "AI analysis returned empty response" -Level "Warning"
            }
            
        } catch {
            Write-OllamaLog "AI analysis failed: $($_.Exception.Message)" -Level "Error"
        }
    }
    
    # Step 3: Generate system overview with AI
    Write-OllamaLog "Generating AI system overview documentation..." -Level "AI"
    
    $systemPrompt = @"
Create comprehensive documentation for the Enhanced Documentation System v2.0.0 based on this information:

System Components:
- Week 1-4: Complete implementation with 337 PowerShell modules
- AI Services: LangGraph (localhost:8000), AutoGen (localhost:8001), Ollama (localhost:11434)  
- Week 4 Features: Code Evolution Analysis, Maintenance Prediction, Technical Debt Analysis
- Visualization: D3.js interactive dashboard with network graphs
- Deployment: Docker containerization with 100% system health

Please create:
1. Executive summary of system capabilities
2. Architecture overview
3. AI integration benefits  
4. Usage scenarios and examples
5. Value proposition for development teams

Format as professional documentation in markdown.
"@
    
    try {
        Write-OllamaLog "Generating AI system overview (may take 90-120 seconds)..." -Level "AI"
        
        $systemAnalysis = Invoke-OllamaGenerate -Prompt $systemPrompt -Model $Model -MaxTokens 6144
        
        if ($systemAnalysis) {
            $systemDoc = @"
# Enhanced Documentation System v2.0.0 - AI-Generated Overview
**Generated by**: Ollama Code Llama 13B
**Timestamp**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
**System Status**: Fully Operational with AI Integration

$systemAnalysis

## Current System Status
- **System Health**: 100% (4/4 services operational)
- **AI Services**: LangGraph + AutoGen + Ollama all available
- **Week 4 Features**: Code Evolution + Maintenance Prediction operational
- **Visualization**: D3.js dashboard with interactive network graphs
- **Documentation Quality**: AI-enhanced with intelligent analysis

## Access Points
- **Documentation**: http://localhost:8080
- **API**: http://localhost:8091
- **LangGraph AI**: http://localhost:8000
- **AutoGen GroupChat**: http://localhost:8001
- **Visualization**: http://localhost:3000
- **Ollama API**: http://localhost:11434

---
*AI-Enhanced Documentation by Enhanced Documentation System v2.0.0*
"@
            
            $systemDoc | Out-File -FilePath "$OutputPath\system-overview-ai-enhanced.md" -Encoding UTF8
            Write-OllamaLog "AI system overview generated: system-overview-ai-enhanced.md" -Level "Success"
            
        } else {
            Write-OllamaLog "AI system overview generation failed" -Level "Warning"
        }
        
    } catch {
        Write-OllamaLog "AI system analysis failed: $($_.Exception.Message)" -Level "Error"
    }
    
    # Step 4: Show generated documentation
    $generatedFiles = Get-ChildItem $OutputPath -Filter "*.md" -ErrorAction SilentlyContinue
    
    Write-OllamaLog "Ollama-enhanced documentation generation complete!" -Level "Success"
    Write-OllamaLog "Generated $($generatedFiles.Count) AI-enhanced documentation files" -Level "Success"
    Write-OllamaLog "Output directory: $OutputPath" -Level "Info"
    
    if ($generatedFiles) {
        Write-OllamaLog "Generated files:" -Level "Info"
        foreach ($file in $generatedFiles) {
            Write-OllamaLog "  • $($file.Name)" -Level "Success"
        }
    }
    
} catch {
    Write-OllamaLog "Ollama documentation generation failed: $($_.Exception.Message)" -Level "Error"
}

Write-Host "`n=== Ollama-Enhanced Documentation Complete ===" -ForegroundColor Green