# Load-MailKitAssemblies.ps1
# Optimized MailKit assembly loading for Unity-Claude notification system
# Auto-generated by Install-MailKit-Fixed.ps1
# Date: 2025-08-21 13:52:15

function Load-MailKitAssemblies {
    [CmdletBinding()]
    param()
    
    try {
        # Check if assemblies are already loaded
        if ([System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.GetName().Name -eq "MimeKit" }) {
            Write-Host "[DEBUG] [MailKit] Assemblies already loaded" -ForegroundColor Gray
            return $true
        }
        
        # Load MimeKit first (dependency)
        Write-Host "[DEBUG] [MailKit] Loading MimeKit assembly..." -ForegroundColor Gray
        Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\MimeKit.4.13.0\lib\net8.0\MimeKit.dll" -ErrorAction Stop
        
        # Load MailKit
        Write-Host "[DEBUG] [MailKit] Loading MailKit assembly..." -ForegroundColor Gray
        Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\MailKit.4.13.0\lib\net8.0\MailKit.dll" -ErrorAction Stop
        
        Write-Host "[SUCCESS] [MailKit] Assemblies loaded successfully" -ForegroundColor Green
        return $true
        
    } catch {
        Write-Warning "[MailKit] Failed to load assemblies: $($_.Exception.Message)"
        return $false
    }
}

# Test loading assemblies
if (Load-MailKitAssemblies) {
    Write-Host "[INFO] [MailKit] Email notification assemblies ready for use" -ForegroundColor White
} else {
    Write-Warning "[MailKit] Email notification assemblies not available"
}

# SIG # Begin signature block
# MIIFqQYJKoZIhvcNAQcCoIIFmjCCBZYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUW2iIrfnwYM0349/loytpY5jI
# w26gggMwMIIDLDCCAhSgAwIBAgIQdR0W2SKoK5VE8JId4ZxrRTANBgkqhkiG9w0B
# AQsFADAuMSwwKgYDVQQDDCNVbml0eS1DbGF1ZGUtQXV0b21hdGlvbi1EZXZlbG9w
# bWVudDAeFw0yNTA4MjAyMTE1MTdaFw0yNjA4MjAyMTM1MTdaMC4xLDAqBgNVBAMM
# I1VuaXR5LUNsYXVkZS1BdXRvbWF0aW9uLURldmVsb3BtZW50MIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAseH3qinVEOhrn2OLpjc5TNT4vGh1BkfB5X4S
# FhY7K0QMQsYYnkZVmx3tB8PqVQXl++l+e3uT7uCscc7vjMTK8tDSWH98ji0U34WL
# JBwXC62l1ArazMKp4Tyr7peksei7vL4pZOtOVgAyTYn5d1hbnsVQmCSTPRtpn7mC
# Azfq2ec5qZ9Kgl7puPW5utvYfh8idtOWa5/WgYSKwOIvyZawIdZKLFpwqOtqbJe4
# sWzVahasFhLfoAKkniKOAocJDkJexh5pO/EOSKEZ3mOCU1ZSs4XWRGISRhV3qGZp
# f+Y3JlHKMeFDWKynaJBO8/GU5sqMATlDUvrByBtU2OQ2Um/L3QIDAQABo0YwRDAO
# BgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFHw5
# rOy6xlW6B45sJUsiI2A/yS0MMA0GCSqGSIb3DQEBCwUAA4IBAQAUTLH0+w8ysvmh
# YuBw4NDKcZm40MTh9Zc1M2p2hAkYsgNLJ+/rAP+I74rNfqguTYwxpCyjkwrg8yF5
# wViwggboLpF2yDu4N/dgDainR4wR8NVpS7zFZOFkpmNPepc6bw3d4yQKa/wJXKeC
# pkRjS50N77/hfVI+fFKNao7POb7en5fcXuZaN6xWoTRy+J4I4MhfHpjZuxSLSXjb
# VXtPD4RZ9HGjl9BU8162cRhjujr/Lc3/dY/6ikHQYnxuxcdxRew4nzaqAQaOeWu6
# tGp899JPKfldM5Zay5IBl3zs15gNS9+0Jrd0ARQnSVYoI0DLh3KybFnfK4POezoN
# Lp/dbX2SMYIB4zCCAd8CAQEwQjAuMSwwKgYDVQQDDCNVbml0eS1DbGF1ZGUtQXV0
# b21hdGlvbi1EZXZlbG9wbWVudAIQdR0W2SKoK5VE8JId4ZxrRTAJBgUrDgMCGgUA
# oHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYB
# BAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0B
# CQQxFgQUjIlhnp6wrrid3V5ST0P7UqQYq88wDQYJKoZIhvcNAQEBBQAEggEAAeN/
# uxU3o/kd1AoYQiM3Xv4PiSRkX+5bFfoXqQ/7UKWdUSHSKMmwRrfU2Ngzm0MRt0A8
# tGdu4cxcEcsy23Y2k9gbdsR8XW/qWYXOsMtjgMvWSjXewlF2qRQ+EqlJPF8cuM+B
# N/H06wwCVnhf61bVR8eZdMmc3/HOp+pXzy9REA6SRAYZVCEQhN3OXIlJCUwfQUfP
# Lygtd7u4ulRBrsvhzjuD+6K/Cp/c5MzzbTXPBnqwyKIekG035Hiyv6YoEQgrk7ay
# KK/RCNsfpPjBu0mAv2KnIyT0Z04eHgAegSxaTma7DHsy0LZ/uO1Y/xqxy3A1RTVg
# 4MvcKVlqvVfw7vwiVA==
# SIG # End signature block
