# Project information
site_name: Unity-Claude-Automation
site_url: https://github.com/Unity-Claude-Automation
site_author: Unity Claude Automation Team
site_description: Comprehensive automation framework for Unity development with Claude AI integration

# Repository
repo_name: Unity-Claude-Automation
repo_url: https://github.com/Unity-Claude-Automation
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Unity Claude Automation

# Theme configuration
theme:
  name: material
  language: en
  
  # Color schemes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Font
  font:
    text: Roboto
    code: Roboto Mono
  
  # Features
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    
    # Table of contents
    - toc.follow
    - toc.integrate
    
    # Search
    - search.suggest
    - search.highlight
    - search.share
    
    # Code blocks
    - content.code.copy
    - content.code.annotate
    - content.code.select
    
    # Content
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  
  # Icons and logos
  icon:
    logo: material/robot-industrial
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      baselevel: 2
      separator: "-"
  
  # PyMdownx extensions for code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Additional PyMdownx extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
  # For critic markup (track changes)
  - pymdownx.critic:
      mode: view

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [scripts]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
    - Architecture: getting-started/architecture.md
  
  - User Guide:
    - Overview: user-guide/overview.md
    - Unity Automation: user-guide/unity-automation.md
    - Claude Integration: user-guide/claude-integration.md
    - System Status Monitoring: user-guide/system-monitoring.md
    - Dashboard: user-guide/dashboard.md
    - Notifications: user-guide/notifications.md
  
  - Modules:
    - Overview: modules/overview.md
    - Unity-Claude-SystemStatus: modules/system-status.md
    - Unity-Claude-Configuration: modules/configuration.md
    - Unity-Claude-EventLog: modules/event-log.md
    - Unity-Claude-GitHub: modules/github.md
    - Unity-Claude-NotificationHub: modules/notification-hub.md
    - Unity-Claude-RepoAnalyst: modules/repo-analyst.md
  
  - API Reference:
    - PowerShell API:
      - Core Functions: api/powershell/core.md
      - System Status: api/powershell/system-status.md
      - Unity Commands: api/powershell/unity-commands.md
      - Monitoring: api/powershell/monitoring.md
      - Configuration: api/powershell/configuration.md
    - Python API:
      - Documentation Parser: api/python/doc-parser.md
      - Static Analysis: api/python/static-analysis.md
    - REST API:
      - Endpoints: api/rest/endpoints.md
      - WebSocket: api/rest/websocket.md
  
  - Advanced Topics:
    - Multi-Agent Architecture: advanced/multi-agent.md
    - Parallel Processing: advanced/parallel-processing.md
    - Event-Driven Patterns: advanced/event-driven.md
    - Performance Optimization: advanced/performance.md
    - Security: advanced/security.md
  
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - CI/CD: development/ci-cd.md
    - Code Style: development/code-style.md
  
  - Resources:
    - Learnings: resources/learnings.md
    - Troubleshooting: resources/troubleshooting.md
    - FAQ: resources/faq.md
    - Glossary: resources/glossary.md
  
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md
    - Roadmap: about/roadmap.md
    - Team: about/team.md

# Extra configuration
extra:
  # Version provider
  version:
    provider: mike
    default: latest
  
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Unity-Claude-Automation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/unity-claude
    - icon: fontawesome/solid/paper-plane
      link: mailto:team@unity-claude.dev
  
  # Analytics (optional)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  
  # Consent
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  
  # Tags (for blog/news if needed)
  tags:
    PowerShell: powershell
    Python: python
    Unity: unity
    Claude: claude
    Automation: automation

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extra CSS
extra_css:
  - stylesheets/extra.css