# AutonomousAgent Subsystem Manifest
# Generated by Migrate-ToManifestSystem.ps1 on 08/22/2025 02:07:37
# Bootstrap Orchestrator Configuration

@{
    # Required fields
    Name = "AutonomousAgent"
    Version = "1.0.0"
    Description = "Autonomous monitoring and response agent for Unity error detection and automated fixes"
    StartScript = ".\Start-AutonomousMonitoring-Fixed.ps1"
    
    # Dependencies
    Dependencies = @("SystemMonitoring")
    
    # Health monitoring
    HealthCheckFunction = "Test-AutonomousAgentStatus"
    HealthCheckInterval = 30  # seconds
    
    # Recovery policy
    RestartPolicy = "OnFailure"  # OnFailure, Always, Never
    MaxRestarts = 3
    RestartDelay = 5  # seconds
    
    # Resource limits
    MaxMemoryMB = 500
    MaxCpuPercent = 25
    
    # Mutex for singleton enforcement
    MutexName = "Global\UnityClaudeAutonomousAgent"
    
    # Migration metadata
    MigratedFrom = "Legacy configuration"
    MigrationDate = "2025-08-22 02:07:37"
    GeneratedBy = "Migrate-ToManifestSystem.ps1"
}
