# CLISubmission Subsystem Manifest
# Generated by Migrate-ToManifestSystem.ps1 on 08/22/2025 02:07:37
# Bootstrap Orchestrator Configuration

@{
    # Required fields
    Name = "CLISubmission"
    Version = "1.0.0"
    Description = "CLI interface for submitting Unity errors to Claude AI for analysis and fixes"
    StartScript = ".\API-Integration\Submit-ErrorsToClaude-API.ps1"
    WorkingDirectory = "C:\UnityProjects\Sound-and-Shoal\Unity-Claude-Automation"
    
    # Dependencies
    Dependencies = @("SystemMonitoring")
    
    # Health monitoring
    HealthCheckFunction = $null
    HealthCheckInterval = 60  # seconds
    
    # Recovery policy
    RestartPolicy = "OnFailure"  # OnFailure, Always, Never
    MaxRestarts = 5
    RestartDelay = 2  # seconds
    
    # Resource limits
    MaxMemoryMB = 200
    MaxCpuPercent = 15
    
    # Mutex for singleton enforcement
    MutexName = "Global\UnityClaudeCLISubmission"
    
    # Migration metadata
    MigratedFrom = "Legacy configuration"
    MigrationDate = "2025-08-22 02:07:37"
    GeneratedBy = "Migrate-ToManifestSystem.ps1"
}
