# SystemMonitoring Subsystem Manifest
# Generated by Migrate-ToManifestSystem.ps1 on 08/22/2025 02:07:37
# Bootstrap Orchestrator Configuration

@{
    # Required fields
    Name = "SystemMonitoring"
    Version = "1.0.0"
    Description = "Core system status monitoring and health tracking subsystem"
    StartScript = ".\Start-SystemStatusMonitoring-Enhanced.ps1"
    
    # Dependencies
    Dependencies = @()
    
    # Health monitoring
    HealthCheckFunction = "Test-SystemStatusHealth"
    HealthCheckInterval = 15  # seconds
    
    # Recovery policy
    RestartPolicy = "Always"  # OnFailure, Always, Never
    MaxRestarts = 10
    RestartDelay = 3  # seconds
    
    # Resource limits
    MaxMemoryMB = 300
    MaxCpuPercent = 20
    
    # Mutex for singleton enforcement
    MutexName = "Global\UnityClaudeSystemMonitoring"
    
    # Migration metadata
    MigratedFrom = "Legacy configuration"
    MigrationDate = "2025-08-22 02:07:37"
    GeneratedBy = "Migrate-ToManifestSystem.ps1"
}
