#
# Module manifest for module 'Unity-Claude-IntegratedWorkflow'
# Phase 1 Week 3 Day 5: End-to-End Integration and Performance Optimization
# Generated by: Unity-Claude-Automation System
# Generated on: 2025-08-21
#

@{
    # Script module or binary module file associated with this manifest.
    # REFACTORED: Now using modular architecture version
    RootModule = 'Unity-Claude-IntegratedWorkflow-Refactored.psm1'
    
    # Version number of this module (Updated for refactored architecture)
    ModuleVersion = '2.0.0'
    
    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')
    
    # ID used to uniquely identify this module
    GUID = '8e3f4a2b-9c7d-4e1f-a2b3-6c8d9e0f1a2b'
    
    # Author of this module
    Author = 'Unity-Claude-Automation System'
    
    # Company or vendor of this module
    CompanyName = 'Unity-Claude Project'
    
    # Copyright statement for this module
    Copyright = '(c) 2025 Unity-Claude Project. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'Complete end-to-end integration system combining Unity compilation parallelization with Claude processing parallelization for autonomous Unity development workflow optimization'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.5'
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # COMMENTED OUT to prevent nesting limit issues
    # RequiredModules = @(
    #     'Unity-Claude-RunspaceManagement',
    #     'Unity-Claude-UnityParallelization', 
    #     'Unity-Claude-ClaudeParallelization'
    # )
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        # End-to-End Workflow Integration (Hour 1-2)
        'New-IntegratedWorkflow',
        'Start-IntegratedWorkflow',
        'Get-IntegratedWorkflowStatus', 
        'Stop-IntegratedWorkflow',
        
        # Performance Optimization Framework (Hour 3-4)
        'Initialize-AdaptiveThrottling',
        'Update-AdaptiveThrottling',
        'New-IntelligentJobBatching',
        'Get-WorkflowPerformanceAnalysis'
    )
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    
    # Variables to export from this module
    VariablesToExport = @()
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
    
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Unity', 'Claude', 'Automation', 'Parallel', 'Integration', 'Workflow', 'Performance', 'DevOps')
            
            # A URL to the license for this module.
            # LicenseUri = ''
            
            # A URL to the main website for this project.
            # ProjectUri = ''
            
            # A URL to an icon representing this module.
            # IconUri = ''
            
            # ReleaseNotes of this module
            ReleaseNotes = @'
Unity-Claude-IntegratedWorkflow v1.0.0 Release Notes

## Week 3 Day 5: End-to-End Integration and Performance Optimization

### New Features:
- Complete Unity-Claude workflow orchestration system
- End-to-end integration from Unity error detection to Claude response processing
- Cross-stage error propagation and handling
- Intelligent job scheduling and dependency management
- Real-time performance monitoring across all workflow stages
- Multiple workflow modes: Continuous, OnDemand, Batch
- Comprehensive health monitoring and status reporting

### Performance Improvements:
- Parallel processing across Unity monitoring and Claude submission stages
- Resource optimization and adaptive throttling
- Workflow orchestration using production-ready runspace pools
- Efficient cross-module communication with synchronized collections

### Architecture:
- Built on Week 2 runspace pool infrastructure (97.92% success rate)
- Integrates Week 3 Days 1-2 Unity parallelization (18 functions)
- Integrates Week 3 Days 3-4 Claude parallelization (8 functions, 100% test success)
- Research-validated patterns from 5+ web queries on workflow orchestration

### Compatibility:
- PowerShell 5.1.22621.5697+ (Windows PowerShell)
- .NET Framework 4.5+
- Unity 2021.1.14f1 (.NET Standard 2.0)
- Full backward compatibility with existing Unity-Claude infrastructure

### Dependencies:
- Unity-Claude-RunspaceManagement (27 functions)
- Unity-Claude-UnityParallelization (18 functions) 
- Unity-Claude-ClaudeParallelization (8 functions)

This module represents the culmination of Week 3 parallel processing implementation,
providing a complete end-to-end Unity development automation solution.
'@
        }
    }
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIIFzgYJKoZIhvcNAQcCoIIFvzCCBbsCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCB9GkGu3TFMw3jP
# Hgn4BYxKp2oEAYLZY1+pVpjS7MeXQaCCAzAwggMsMIICFKADAgECAhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMMI1VuaXR5LUNsYXVk
# ZS1BdXRvbWF0aW9uLURldmVsb3BtZW50MB4XDTI1MDgyMDIxMTUxN1oXDTI2MDgy
# MDIxMzUxN1owLjEsMCoGA1UEAwwjVW5pdHktQ2xhdWRlLUF1dG9tYXRpb24tRGV2
# ZWxvcG1lbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCx4feqKdUQ
# 6GufY4umNzlM1Pi8aHUGR8HlfhIWFjsrRAxCxhieRlWbHe0Hw+pVBeX76X57e5Pu
# 4Kxxzu+MxMry0NJYf3yOLRTfhYskHBcLraXUCtrMwqnhPKvul6Sx6Lu8vilk605W
# ADJNifl3WFuexVCYJJM9G2mfuYIDN+rZ5zmpn0qCXum49bm629h+HyJ205Zrn9aB
# hIrA4i/JlrAh1kosWnCo62psl7ixbNVqFqwWEt+gAqSeIo4ChwkOQl7GHmk78Q5I
# oRneY4JTVlKzhdZEYhJGFXeoZml/5jcmUcox4UNYrKdokE7z8ZTmyowBOUNS+sHI
# G1TY5DZSb8vdAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzAdBgNVHQ4EFgQUfDms7LrGVboHjmwlSyIjYD/JLQwwDQYJKoZIhvcN
# AQELBQADggEBABRMsfT7DzKy+aFi4HDg0MpxmbjQxOH1lzUzanaECRiyA0sn7+sA
# /4jvis1+qC5NjDGkLKOTCuDzIXnBWLCCBugukXbIO7g392ANqKdHjBHw1WlLvMVk
# 4WSmY096lzpvDd3jJApr/Alcp4KmRGNLnQ3vv+F9Uj58Uo1qjs85vt6fl9xe5lo3
# rFahNHL4ngjgyF8emNm7FItJeNtVe08PhFn0caOX0FTzXrZxGGO6Ov8tzf91j/qK
# QdBifG7Fx3FF7DifNqoBBo55a7q0anz30k8p+V0zllrLkgGXfOzXmA1L37Qmt3QB
# FCdJVigjQMuHcrJsWd8rg857Og0un91tfZIxggH0MIIB8AIBATBCMC4xLDAqBgNV
# BAMMI1VuaXR5LUNsYXVkZS1BdXRvbWF0aW9uLURldmVsb3BtZW50AhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIKVfqwuWyGZ/Acj/iFqrap2i
# aU64znTCe4LdbXLXZQxxMA0GCSqGSIb3DQEBAQUABIIBAFSVcwfv986aPNv3jFrc
# e6F0OeHpgAcCV/rAGORjdaJF+7MTzCpuZxI02MQPsIS99x0eltr2PQ6PfMHtc2zB
# FeXddXeJ4KzzZSqDIhvkoYytmsYbW7NdzSo/U5Bcr03mRQuEGmTWB+xZ+mqZ6gU9
# WhlcT4EvWWVjGRk3b2p77uPzxLGb/wqXtGm7XZ96BYKY1K+7pxr04VZ3QabQ9MTB
# f7fZKqTWRIPthhCN2o0VCWx3d/7eJaPF953+9oYec+CWSnM1EKq2y6EgOqLBj2Yj
# u4GCHQex9qI8S7sqerka/sJ4iSGKP9hJ5esm6H1HbELMSouxd2yao8UcWLK7MZpp
# oDQ=
# SIG # End signature block
