# Prometheus Configuration
# Unity-Claude Automation Monitoring
# Version: 2025-08-24

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'unity-claude-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      scheme: http
      timeout: 10s

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 5s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 15s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Unity-Claude Services
  - job_name: 'langgraph-api'
    static_configs:
      - targets: ['langgraph-api:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'langgraph-api'
      - source_labels: []
        target_label: service
        replacement: 'langgraph'

  - job_name: 'autogen-groupchat'
    static_configs:
      - targets: ['autogen-groupchat:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'autogen-groupchat'
      - source_labels: []
        target_label: service
        replacement: 'autogen'

  - job_name: 'powershell-modules'
    static_configs:
      - targets: ['powershell-modules:5985']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'powershell-modules'
      - source_labels: []
        target_label: service
        replacement: 'powershell'

  # Health check endpoints
  - job_name: 'health-checks'
    metrics_path: /health
    scrape_interval: 30s
    static_configs:
      - targets:
          - 'langgraph-api:8000'
          - 'autogen-groupchat:8001'
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: service_name
        replacement: '${1}'

  # Blackbox exporter for endpoint monitoring (if deployed)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://langgraph-api:8000/health
          - http://autogen-groupchat:8001/health
          - http://grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Service discovery for Docker containers (optional)
  - job_name: 'docker-containers'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service_name
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep