#
# Module manifest for module 'Unity-Claude-ObsolescenceDetection-Refactored'
#
# Generated by: Unity-Claude-Automation Framework
#
# Generated on: 8/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Unity-Claude-ObsolescenceDetection-Refactored.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '12345678-1234-5678-9012-123456789abc'

# Author of this module
Author = 'Unity-Claude-Automation Framework'

# Company or vendor of this module
CompanyName = 'Unity-Claude'

# Copyright statement for this module
Copyright = '(c) 2025 Unity-Claude-Automation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Refactored Unity Claude CPG Obsolescence Detection Module v2.0.0

ARCHITECTURE: Component-Based Modular Design
COMPONENTS: 6 specialized components under 800 lines each
MIGRATION: From monolithic 1,806-line module to maintainable architecture

Components:
- DePA Algorithm: Dead Program Artifact detection using statistical language modeling
- Graph Traversal: Unreachable code detection using breadth-first search analysis  
- Code Redundancy Detection: Duplicate and similar code pattern identification
- Code Complexity Metrics: Comprehensive complexity analysis with risk assessment
- Documentation Comparison: Code-to-documentation drift analysis and validation
- Documentation Accuracy: Accuracy testing and automated suggestion generation

Features:
- Multi-language support (PowerShell, JavaScript, TypeScript, Python, C#)
- Advanced statistical analysis using perplexity and entropy measurements
- Comprehensive graph traversal algorithms for reachability analysis
- Structural and semantic similarity detection for clone identification
- Cyclomatic and cognitive complexity calculations with maintainability metrics
- Documentation quality scoring and automated improvement suggestions
- Integrated orchestration with comprehensive analysis workflows
- Component health monitoring and integration testing
- Prioritized action plans for addressing obsolescence issues

This refactored version provides the same functionality as the original module
while offering improved maintainability, testability, and extensibility.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'Unity-Claude-CPG'; ModuleVersion = '1.0.0'; }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'Core\DepaAlgorithm.psm1',
    'Core\GraphTraversal.psm1', 
    'Core\CodeRedundancyDetection.psm1',
    'Core\CodeComplexityMetrics.psm1',
    'Core\DocumentationComparison.psm1',
    'Core\DocumentationAccuracy.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # DePA Algorithm Component
    'Get-LinePerplexity',
    'Test-DeadProgramArtifacts',
    
    # Graph Traversal Component  
    'Find-UnreachableCode',
    
    # Code Redundancy Detection Component
    'Test-CodeRedundancy',
    'Find-DuplicateFunctions', 
    'Find-SimilarCodeBlocks',
    'Find-CloneGroups',
    
    # Code Complexity Metrics Component
    'Get-CodeComplexityMetrics',
    'Get-FunctionComplexity',
    'Get-ClassComplexity',
    
    # Documentation Comparison Component
    'Compare-CodeToDocumentation',
    'Find-UndocumentedFeatures',
    
    # Documentation Accuracy Component
    'Test-DocumentationAccuracy',
    'Update-DocumentationSuggestions',
    
    # Orchestrator Functions
    'Get-ObsolescenceDetectionComponents',
    'Test-ObsolescenceDetectionHealth',
    'Invoke-ComprehensiveObsolescenceAnalysis'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Unity-Claude-ObsolescenceDetection-Refactored.psm1',
    'Unity-Claude-ObsolescenceDetection-Refactored.psd1',
    'Core\DepaAlgorithm.psm1',
    'Core\GraphTraversal.psm1',
    'Core\CodeRedundancyDetection.psm1', 
    'Core\CodeComplexityMetrics.psm1',
    'Core\DocumentationComparison.psm1',
    'Core\DocumentationAccuracy.psm1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Unity-Claude', 'CPG', 'ObsolescenceDetection', 'CodeAnalysis', 'DeadCode', 
            'Refactoring', 'CodeQuality', 'StaticAnalysis', 'DocumentationDrift', 
            'ComplexityMetrics', 'RedundancyDetection', 'GraphTraversal', 'Modular',
            'Component-Based', 'PowerShell', 'Automation', 'DePA', 'BFS', 'Entropy',
            'Perplexity', 'Clone-Detection', 'Maintainability', 'Technical-Debt'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Unity-Claude-Automation/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Unity-Claude-Automation'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Unity Claude CPG Obsolescence Detection v2.0.0 - Refactored Modular Architecture

MAJOR REFACTORING RELEASE
========================

Migration Summary:
- Original: Unity-Claude-ObsolescenceDetection.psm1 (1,806 lines, monolithic)  
- Refactored: 6 focused components (202-568 lines each, all under 800-line limit)
- Architecture: Component-based modular design with orchestration layer
- Maintainability: Dramatically improved with focused responsibilities
- Testing: Individual component testing with health monitoring
- Extensibility: Easy to add new components or modify existing ones

Component Breakdown:
1. DepaAlgorithm.psm1 (202 lines): Dead Program Artifact detection using statistical language modeling
2. GraphTraversal.psm1 (160 lines): Unreachable code detection using BFS graph traversal  
3. CodeRedundancyDetection.psm1 (392 lines): Duplicate and similar code pattern identification
4. CodeComplexityMetrics.psm1 (449 lines): Comprehensive complexity analysis and risk assessment
5. DocumentationComparison.psm1 (486 lines): Code-to-documentation drift analysis
6. DocumentationAccuracy.psm1 (568 lines): Documentation accuracy testing and suggestions

New Features in v2.0.0:
- Component health monitoring with Test-ObsolescenceDetectionHealth
- Comprehensive analysis orchestration with Invoke-ComprehensiveObsolescenceAnalysis
- Component information retrieval with Get-ObsolescenceDetectionComponents
- Enhanced error handling and component validation
- Modular import system with graceful degradation
- Integration testing between components
- Prioritized action plan generation
- Advanced documentation suggestion engine

Technical Improvements:
- Each component follows PowerShell best practices
- Comprehensive parameter validation and error handling
- Verbose logging for troubleshooting and monitoring
- Component isolation for better testing and maintenance
- Consistent API design across all components
- Enhanced documentation with detailed examples
- Performance optimizations through component specialization

Backward Compatibility:
- All original functions maintained with same signatures
- Seamless drop-in replacement for existing installations
- Enhanced functionality without breaking changes
- Migration path documented for custom implementations

Migration Benefits:
- Reduced cognitive load for maintenance and development
- Individual component testing and validation
- Easier troubleshooting with component isolation  
- Better performance through specialized implementations
- Enhanced extensibility for future enhancements
- Improved code quality and maintainability metrics

This refactored version represents a significant improvement in code quality,
maintainability, and extensibility while preserving all original functionality.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('Unity-Claude-CPG')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
# SIG # Begin signature block
# MIIFzgYJKoZIhvcNAQcCoIIFvzCCBbsCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDEz4lKw1CBw1k6
# 0wDVD9vMozXrC15tqeOT10a0IJasEaCCAzAwggMsMIICFKADAgECAhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMMI1VuaXR5LUNsYXVk
# ZS1BdXRvbWF0aW9uLURldmVsb3BtZW50MB4XDTI1MDgyMDIxMTUxN1oXDTI2MDgy
# MDIxMzUxN1owLjEsMCoGA1UEAwwjVW5pdHktQ2xhdWRlLUF1dG9tYXRpb24tRGV2
# ZWxvcG1lbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCx4feqKdUQ
# 6GufY4umNzlM1Pi8aHUGR8HlfhIWFjsrRAxCxhieRlWbHe0Hw+pVBeX76X57e5Pu
# 4Kxxzu+MxMry0NJYf3yOLRTfhYskHBcLraXUCtrMwqnhPKvul6Sx6Lu8vilk605W
# ADJNifl3WFuexVCYJJM9G2mfuYIDN+rZ5zmpn0qCXum49bm629h+HyJ205Zrn9aB
# hIrA4i/JlrAh1kosWnCo62psl7ixbNVqFqwWEt+gAqSeIo4ChwkOQl7GHmk78Q5I
# oRneY4JTVlKzhdZEYhJGFXeoZml/5jcmUcox4UNYrKdokE7z8ZTmyowBOUNS+sHI
# G1TY5DZSb8vdAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzAdBgNVHQ4EFgQUfDms7LrGVboHjmwlSyIjYD/JLQwwDQYJKoZIhvcN
# AQELBQADggEBABRMsfT7DzKy+aFi4HDg0MpxmbjQxOH1lzUzanaECRiyA0sn7+sA
# /4jvis1+qC5NjDGkLKOTCuDzIXnBWLCCBugukXbIO7g392ANqKdHjBHw1WlLvMVk
# 4WSmY096lzpvDd3jJApr/Alcp4KmRGNLnQ3vv+F9Uj58Uo1qjs85vt6fl9xe5lo3
# rFahNHL4ngjgyF8emNm7FItJeNtVe08PhFn0caOX0FTzXrZxGGO6Ov8tzf91j/qK
# QdBifG7Fx3FF7DifNqoBBo55a7q0anz30k8p+V0zllrLkgGXfOzXmA1L37Qmt3QB
# FCdJVigjQMuHcrJsWd8rg857Og0un91tfZIxggH0MIIB8AIBATBCMC4xLDAqBgNV
# BAMMI1VuaXR5LUNsYXVkZS1BdXRvbWF0aW9uLURldmVsb3BtZW50AhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIOTP2mBKQZ9+Y/4urzUibiDC
# 67N7AmC/x0Jm3Y+EHIRYMA0GCSqGSIb3DQEBAQUABIIBACPjJkCXYLa3juyr8yPg
# bNrq9TV0BzOSpqdsVywvBVTCcQxAvtODzVJF8adeYimdu7gc3JueRTCOCKN4G23y
# 2//KTbbXbCljDlqXyPxJDQAaGgckZIec5aV0KPpdVgLzOgupvCe14VYkz8sDi0j0
# iaMElVHTM6zVcxGxAwgVTc913frytcEZUjwOr4VOiPN6ucj6tznVHZplOGzYPsjC
# BY4ZlW5peBXY//UWrrJt+KtsRSqMDxlQv6cffJKFdRBhyTAttzOFgyEaUhfoIyaR
# 8vI8UJcaUhwHw3s+3WaPw/0V5DL2cwuCUJUuo0LYHTgINAi42fV0uQCDHQWR9Ffi
# uL0=
# SIG # End signature block
