#
# Module manifest for module 'Unity-Claude-PredictiveAnalysis-Refactored'
#
# Generated by: Unity-Claude-Automation Framework
#
# Generated on: 8/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Unity-Claude-PredictiveAnalysis.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f8e9d6c7-4b5a-3e2f-9d8c-7b6a5e4f3d2c'

# Author of this module
Author = 'Unity-Claude-Automation Framework'

# Company or vendor of this module
CompanyName = 'Unity-Claude-Automation'

# Copyright statement for this module
Copyright = '(c) Unity-Claude-Automation Framework. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Refactored Unity Claude Predictive Analysis Module - Modular architecture providing comprehensive code analysis, maintenance prediction, refactoring detection, code smell analysis, risk assessment, and improvement roadmap generation with ROI analysis. Features 8 specialized components for enhanced maintainability and performance.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'Core\PredictiveCore.psm1',
    'Core\TrendAnalysis.psm1',
    'Core\MaintenancePrediction.psm1', 
    'Core\RefactoringDetection.psm1',
    'Core\CodeSmellPrediction.psm1',
    'Core\ImprovementRoadmaps.psm1',
    'Core\RiskAssessment.psm1',
    'Core\AnalyticsReporting.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core Functions
    'Initialize-PredictiveCache', 'Clear-PredictiveCache', 'Get-CacheStats',
    
    # Trend Analysis Functions
    'Get-CodeEvolutionTrend', 'Measure-CodeChurn', 'Find-CodeHotspots',
    
    # Maintenance Prediction Functions
    'Get-MaintenancePrediction', 'Calculate-TechnicalDebt', 'Get-MaintenanceScore',
    
    # Refactoring Detection Functions
    'Find-RefactoringOpportunities', 'Find-LongMethods', 'Find-LargeClasses',
    'Get-DuplicationCandidates', 'Find-DeadCode',
    
    # Code Smell Prediction Functions
    'Predict-CodeSmells', 'Get-SmellDetails', 'Get-RemediationAdvice',
    
    # Improvement Roadmap Functions
    'New-ImprovementRoadmap', 'Export-RoadmapReport', 'Get-RoadmapPhases',
    
    # Risk Assessment Functions
    'Predict-BugProbability', 'Get-MaintenanceRisk', 'Find-AntiPatterns', 'Get-DesignFlaws',
    
    # Analytics & Reporting Functions
    'Get-ROIAnalysis', 'Get-HistoricalMetrics', 'Get-ComplexityTrend',
    'Get-CommitFrequency', 'Get-AuthorContributions', 'Update-PredictionModels',
    'Estimate-RefactoringEffort', 'Get-PriorityActions', 'Get-CouplingIssues',
    
    # Orchestrator Functions
    'Initialize-PredictiveAnalysis', 'Get-ComprehensiveAnalysis'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('gct', 'gmp', 'fro', 'pcs', 'nir')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Unity', 'Claude', 'Automation', 'PredictiveAnalysis', 'CodeAnalysis', 'Maintenance', 'Refactoring', 'CodeSmells', 'TechnicalDebt', 'ROI', 'RiskAssessment', 'CodeMetrics', 'Modular')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'v2.0.0 - Major refactoring to modular architecture:
- Broke 2,094-line monolithic module into 8 focused components
- PredictiveCore: Core initialization and cache management (288 lines)
- TrendAnalysis: Code evolution and churn analysis (314 lines) 
- MaintenancePrediction: Maintenance scoring and technical debt (327 lines)
- RefactoringDetection: Refactoring opportunity identification (569 lines)
- CodeSmellPrediction: Code smell detection with confidence scoring (658 lines)
- ImprovementRoadmaps: Comprehensive roadmap generation (1,052 lines)
- RiskAssessment: Bug probability and maintenance risk analysis (890 lines)
- AnalyticsReporting: ROI analysis and historical metrics (622 lines)
- Enhanced maintainability, testability, and performance
- Consistent error handling and logging patterns
- Improved cache management with TTL support
- Better separation of concerns and dependency management'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

# SIG # Begin signature block
# MIIFzgYJKoZIhvcNAQcCoIIFvzCCBbsCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBpur4gO3GnKgrX
# NR+OSgf2Rj5xR0G+b0fgow72ehdNXKCCAzAwggMsMIICFKADAgECAhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMMI1VuaXR5LUNsYXVk
# ZS1BdXRvbWF0aW9uLURldmVsb3BtZW50MB4XDTI1MDgyMDIxMTUxN1oXDTI2MDgy
# MDIxMzUxN1owLjEsMCoGA1UEAwwjVW5pdHktQ2xhdWRlLUF1dG9tYXRpb24tRGV2
# ZWxvcG1lbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCx4feqKdUQ
# 6GufY4umNzlM1Pi8aHUGR8HlfhIWFjsrRAxCxhieRlWbHe0Hw+pVBeX76X57e5Pu
# 4Kxxzu+MxMry0NJYf3yOLRTfhYskHBcLraXUCtrMwqnhPKvul6Sx6Lu8vilk605W
# ADJNifl3WFuexVCYJJM9G2mfuYIDN+rZ5zmpn0qCXum49bm629h+HyJ205Zrn9aB
# hIrA4i/JlrAh1kosWnCo62psl7ixbNVqFqwWEt+gAqSeIo4ChwkOQl7GHmk78Q5I
# oRneY4JTVlKzhdZEYhJGFXeoZml/5jcmUcox4UNYrKdokE7z8ZTmyowBOUNS+sHI
# G1TY5DZSb8vdAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzAdBgNVHQ4EFgQUfDms7LrGVboHjmwlSyIjYD/JLQwwDQYJKoZIhvcN
# AQELBQADggEBABRMsfT7DzKy+aFi4HDg0MpxmbjQxOH1lzUzanaECRiyA0sn7+sA
# /4jvis1+qC5NjDGkLKOTCuDzIXnBWLCCBugukXbIO7g392ANqKdHjBHw1WlLvMVk
# 4WSmY096lzpvDd3jJApr/Alcp4KmRGNLnQ3vv+F9Uj58Uo1qjs85vt6fl9xe5lo3
# rFahNHL4ngjgyF8emNm7FItJeNtVe08PhFn0caOX0FTzXrZxGGO6Ov8tzf91j/qK
# QdBifG7Fx3FF7DifNqoBBo55a7q0anz30k8p+V0zllrLkgGXfOzXmA1L37Qmt3QB
# FCdJVigjQMuHcrJsWd8rg857Og0un91tfZIxggH0MIIB8AIBATBCMC4xLDAqBgNV
# BAMMI1VuaXR5LUNsYXVkZS1BdXRvbWF0aW9uLURldmVsb3BtZW50AhB1HRbZIqgr
# lUTwkh3hnGtFMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIJ+Iy0MBwJeunV2bysOZfPoZ
# C0qWLTKyhKuOnFQX/BP2MA0GCSqGSIb3DQEBAQUABIIBAK24kIE3W35bswP9/IER
# gE5QVZOsJnc91HAINf2tWasJqlJ5BwkSmwlglVQxgYoZAv8w62VRILpq1rbHW029
# w07OEAoaHHNEnedO54vPFClvUGCY6T8fDnxTxAwytq0489zl4QYJQuFdEVjiD+LB
# G+FXv0jSyR4bk1EliJXd++kRNVn1ZxaVeGucPPrAyd4QiSeTJJyOegbabVr5x2X5
# 6UtHmqJ6kclx9vaXnplzLUO3cBaSYPl3hqtf8S0sU7MSbEBmDEwTSV8SNv1ITNN5
# keWkLnWXMfpBhrgwmJo4kgqT1TqLFm/tMcHm1lVr68s0UUHGneQ1fCet4WIkbV6p
# O68=
# SIG # End signature block
