#
# Module manifest for module 'Unity-Claude-Ollama'
#
# Generated by: Unity-Claude Automation System
#
# Generated on: 2025-08-30
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Unity-Claude-Ollama.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f4e8d9c2-3b7a-4f1e-9c8d-2a5b6e3f4c7d'

# Author of this module
Author = 'Unity-Claude Automation System'

# Company or vendor of this module
CompanyName = 'Unity-Claude'

# Copyright statement for this module
Copyright = '(c) Unity-Claude Automation System. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Unity-Claude-Ollama: Enhanced local AI integration module for AI-enhanced documentation generation using Ollama and CodeLlama models. Provides 13 comprehensive PowerShell wrapper functions with timeout optimization, model preloading, retry logic, and performance monitoring for production-ready local AI operations.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Start-OllamaService',
    'Stop-OllamaService',
    'Test-OllamaConnectivity', 
    'Get-OllamaModelInfo',
    'Set-OllamaConfiguration',
    'Invoke-OllamaDocumentation',
    'Invoke-OllamaCodeAnalysis',
    'Invoke-OllamaExplanation',
    'Start-ModelPreloading',
    'Format-DocumentationPrompt',
    'Invoke-OllamaRetry',
    'Get-OllamaPerformanceMetrics',
    'Export-OllamaConfiguration'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('AI', 'Ollama', 'Documentation', 'CodeLlama', 'LocalAI', 'Unity', 'Claude', 'Automation')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Week 1 Day 3 Hour 1-2: Initial Ollama Local AI Integration
        
Features:
- 12 comprehensive functions for AI-enhanced documentation
- CodeLlama model integration with 32K context window support
- Comprehensive error handling with exponential backoff retry logic
- Performance monitoring and metrics collection
- PowerShell 5.1 compatibility validated
- Integration with existing Unity-Claude automation framework
        
Functions:
- Service Management: Start/Stop-OllamaService, Test-OllamaConnectivity
- Model Management: Get-OllamaModelInfo, Set-OllamaConfiguration
- Documentation Generation: Invoke-OllamaDocumentation, Invoke-OllamaCodeAnalysis, Invoke-OllamaExplanation
- Utility Functions: Format-DocumentationPrompt, Invoke-OllamaRetry
- Monitoring: Get-OllamaPerformanceMetrics, Export-OllamaConfiguration'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}