name: Build iOS App

on:
  push:
    branches: [ main ]
    paths: [ 'iOS-App/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'iOS-App/**' ]
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache SPM dependencies
      uses: actions/cache@v4
      with:
        path: iOS-App/AgentDashboard/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('iOS-App/AgentDashboard/Package.swift') }}
        
    - name: Build iOS App
      run: |
        cd iOS-App/AgentDashboard
        swift build
        
    - name: Run Tests
      run: |
        cd iOS-App/AgentDashboard  
        swift test
        
    - name: Build for iOS Simulator (Demo)
      run: |
        cd iOS-App/AgentDashboard
        xcodebuild -scheme AgentDashboard -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
        
    - name: Archive Build Results
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: iOS-App/AgentDashboard/.build